<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\App.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="StringsTests.fs" />
    <Compile Include="PreferencesTests.fs" />
    <Compile Include="UtilsTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
